.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. kingpepe_qt test_kingpepe_qt
clean: FORCE
	$(MAKE) -C .. kingpepe_qt_clean test_kingpepe_qt_clean
check: FORCE
	$(MAKE) -C .. test_kingpepe_qt_check
kingpepe-qt kingpepe-qt.exe: FORCE
	 $(MAKE) -C .. kingpepe_qt
apk: FORCE
	$(MAKE) -C .. kingpepe_qt_apk
