.TH KINGPEPE-UTIL 1
.SH NAME
kingpepe-util \- standalone KingPepe Core utility commands
.SH SYNOPSIS
.B kingpepe-util
[\fIOPTIONS\fR] [\fICOMMAND\fR]
.SH DESCRIPTION
The
.B kingpepe-util
tool provides KingPepe-related utilities that do not require access to a running
node.
.SH OPTIONS
Run
.B kingpepe-util -help
for the complete option list supported by this build.
.SH SEE ALSO
.BR kingpepe-cli (1)
