.TH KINGPEPE-CLI 1
.SH NAME
kingpepe-cli \- command-line RPC client for KingPepe Core
.SH SYNOPSIS
.B kingpepe-cli
[\fIOPTIONS\fR] \fICOMMAND\fR [\fIPARAMS\fR]
.SH DESCRIPTION
The
.B kingpepe-cli
utility sends RPC commands to a running
.B kingpeped
or
.B kingpepe-qt
node.
.SH OPTIONS
Run
.B kingpepe-cli -help
for the complete option list supported by this build.
.SH SEE ALSO
.BR kingpeped (1),
.BR kingpepe-qt (1)
